# Generated by Django 5.0.2 on 2024-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('revenue', models.FloatField()),
                ('gp', models.FloatField()),
                ('fcf', models.FloatField()),
                ('capex', models.FloatField()),
            ],
        ),
    ]
