# Generated by Django 5.0.2 on 2024-03-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='fcf',
            field=models.FloatField(default=0),
        ),
    ]
