# Generated by Django 5.0.2 on 2024-03-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker_api_app', '0002_alter_ticker_fcf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='capex',
            field=models.FloatField(default=0),
        ),
    ]
